on:
  release:
    types: [published]

concurrency:
  group: "build"
  cancel-in-progress: true

env:
  MODRINTH_ID: "${{ vars.MODRINTH_ID }}"
  CURSEFORGE_ID: "${{ vars.CURSEFORGE_ID }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"
      - name: Change Version
        run: sed -i 's/mod_version=.*/mod_version=${{ github.event.release.tag_name }}/g' gradle.properties
      - name: Build
        run: ./gradlew clean build
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: "${{ env.CURSEFORGE_ID }}"
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"
          curseforge-version-type: "${{ steps.get-release.outputs.release-type }}"
          modrinth-id: "${{ env.MODRINTH_ID }}"
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
          modrinth-version-type: "${{ steps.get-release.outputs.release-type }}"
          github-tag: "${{ github.event.release.tag_name }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "${{ github.event.release.name }}"
          version: "${{ github.event.release.tag_name }}"
          version-type: "${{ github.event.release.prerelease && 'beta' || 'release' }}"
          changelog: "${{ github.event.release.body }}"
